services:
  ros2:
    build: .
    network_mode: host
    ipc: host
    volumes:
      - /home/pi5/spot_micro:/home/ros
    devices:
      - /dev/i2c-1
      - /dev/gpiomem0
      - /dev/gpiochip0
    tty: true
