FROM ros:jazzy-ros-base
RUN apt-get update && apt-get install --no-install-recommends -y \
    build-essential \
    git \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-vcstool \
    nano \
    python3-pip \
    i2c-tools \
    && rm -rf /var/lib/apt/lists/*
RUN rm -f /etc/ros/rosdep/sources.list.d/20-default.list && rosdep init && rosdep update --rosdistro $ROS_DISTRO
RUN apt-get update && apt-get install -y --no-install-recommends \
    ros-jazzy-foxglove-bridge \
    ros-jazzy-v4l2-camera
RUN pip install smbus2 lgpio pytest --break-system-packages
RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc


